[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["app"]
known_third_party = ["fastapi", "pydantic", "uuid", "supabase"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.ruff]
line-length = 88
target-version = "py311"
extend-select = ["I", "F", "E", "W"]
ignore = ["E501"]  # Ignorar línea muy larga si usas Black
exclude = ["migrations", "__pycache__"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # Ignora imports no usados en __init__.py